### ISSUE TITLE
Working with Home Assistant - core

### ISSUE THREAD

**Issue by hollapm** [quielb/homeassistant-custom-components#1]
Were you able to get this working with home assistant?  I tried adding the fan and Airscape to the latest version and received an error.  Would LOVE to see this working ;-)

**Comment by quielb** [comment]
The version that is here is an older version.  I haven't updated it a while.  I am currently running a working version on my production system.  I've been working on the component to support config flow setup instead of YAML config.  I also want to make the component HACS "compliant"  so that it can be pulled via HACS.  Give me a few days to get the latest version cleaned up and updated.

**Comment by hollapm** [comment]
That would be fantastic.  I have HACS implemented so that would make it easy.  Is it able to see all 10 speeds of the fan?

**Comment by quielb** [comment]
Yes it does support all 10 speeds. That is the main reason while this will always exist as a custom component. The current architecture in HA only supports fans with speed of off, low, medium, and high. There is an on-going ticket which gets some occasional discussion about changing that architecture. But it hasn't moved anywhere in about 2 years.

Since this will always be a custom component, that is what is driving me to get it working with HACS.  It will make it easier to maintain in the long run, using HACS to pull current versions of the component.

**Comment by quielb** [comment]
I've put the current production code in a new repo to start building out the structure to support HACS.  I am going to deprecate this repo.  You can find the other repo here [hass-airscape](https://github.com/quielb/hass-airscape).

This is just the bare working code.  You will have to pull it and deploy it by hand until I get all the steps for HASS integration done.

**Comment by hollapm** [comment]
Thanks, I'll review.  Need to figure out how to implement with my version of home assistant. will likely play with it this coming weekend.
